config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :pull_requests do
    collection do
      post 'sorted', to: 'pull_requests#sorted', as: 'sorted'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pull_requests#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope { order('lower(name)') }

  has_many :pull_request

  def pretty_name
    if name == ""
      "Uncategorized"
    else
      name
    end
  end
end

app/models/pull_request.rb
# frozen_string_literal: true

class PullRequest < ApplicationRecord
  enum :test_priority, [ :unknown, :no, :maybe, :yes ], default: :unknown

  belongs_to :category
  has_markdown :notes

  before_validation :set_nil_category, unless: -> { category.present? }

  def set_nil_category
    self.category = Category.find_or_create_by(name: "")
  end

  # Returns a `PullRequest` object from a pr #
  # Expects PR to be merged.
  def self.from_number(number:, repository: "bitcoin/bitcoin")
    gh_client = Octokit::Client.new(access_token: Rails.application.credentials.github_oauth_key)
    octo_pr = gh_client.pull_request(repository, number)

    new(
      number:,
      repository:,
      url: octo_pr.html_url,
      title: octo_pr.title,
      merged_at: octo_pr.merged_at
    )
  end

  def sort(sort:, order:)
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/pull_requests_controller.rb
class PullRequestsController < ApplicationController
  before_action :set_pull_request, only: %i[ show edit update destroy ]

  # GET /pull_requests or /pull_requests.json
  def index
    @sort = params[:sort] || :merged_at
    @order = params[:order] || :asc
    @category_filter = params[:category_filter] || Category.pluck(:id)

    if @sort == "category"
      @pull_requests = PullRequest.joins(:category).order("categories.name #{@order}")
    else
      @pull_requests = PullRequest.order(@sort => @order)
    end
  end

  def sorted
    @sort = params[:sort] || :merged_at
    @order = params[:order] || :asc
    @category_filter = params[:category_filter] || Category.pluck(:id)

    if @sort == "category"
      @pull_requests = PullRequest.joins(:category).order("categories.name #{@order}")
    else
      @pull_requests = PullRequest.order(@sort => @order)
    end

    render :index, status: 422
  end

  # GET /pull_requests/1 or /pull_requests/1.json
  def show
  end

  # GET /pull_requests/new
  def new
    @pull_request = PullRequest.new
  end

  # GET /pull_requests/1/edit
  def edit
  end

  # POST /pull_requests or /pull_requests.json
  def create
    @pull_request = PullRequest.new(pull_request_params)

    respond_to do |format|
      if @pull_request.save
        format.html { redirect_to pull_request_url(@pull_request), notice: "Pull request was successfully created." }
        format.json { render :show, status: :created, location: @pull_request }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pull_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pull_requests/1 or /pull_requests/1.json
  def update
    respond_to do |format|
      if @pull_request.update(pull_request_params)
        format.html { redirect_to pull_request_url(@pull_request), notice: "Pull request was successfully updated." }
        format.json { render :show, status: :ok, location: @pull_request }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pull_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pull_requests/1 or /pull_requests/1.json
  def destroy
    @pull_request.destroy!

    respond_to do |format|
      format.html { redirect_to pull_requests_url, notice: "Pull request was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pull_request
      @pull_request = PullRequest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pull_request_params
      params.require(:pull_request).permit(:num, :url, :title, :repository, :notes, :category_id, :merged_at, :test_priority)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pull_requests_helper.rb
module PullRequestsHelper
  def category_select_options(selected:)
    options_from_collection_for_select(Category.all, 'id', 'name', selected)
  end 

  def pull_request_sort_select_options(selected:)
    options_for_select([
      ["Date", "merged_at"],
      ["Test Priority", "test_priority"],
      ["Category", "category"]
    ], selected)
  end
end

app/views/action_markdown/contents/_content.html.erb
<div class="action-markdown">
  <%= sanitize content.to_html %>
</div>

app/views/categories/_category.html.erb
<div class="categories-index" id="<%= dom_id category %>">
    <%= category.name %>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<%= link_to "Add a category", new_category_path %>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
  <% end %>
</div>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Core 27.0 RC Testing Guide</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="turbo-refresh-method" content="morph">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://cdn.simplecss.org/simple.min.css",
                            "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <nav>
        <ul>
          <li><%= link_to "Pull Requests", pull_requests_path %></li>
          <li><%= link_to "Categories", categories_path %></li>
        </ul>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/pull_requests/_form.html.erb
<%= form_with(model: pull_request) do |form| %>
  <div class="pull-request-box">
    <% if pull_request.errors.any? %>
      <div class="pull-request-errors" style="color: red">
        <h2><%= pluralize(pull_request.errors.count, "error") %> prohibited this PR from being saved:</h2>
        <ul>
          <% pull_request.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="pull-request-info">
      <%= link_to "#{pull_request.repository}\##{pull_request.number}", pull_request.url %>
      <div><%= pull_request.title %></div>
      <div class="pull-request-time"><%= pull_request.merged_at&.strftime("%Y-%m-%d %H:%M") %></div>
    </div>
    <div class="pull-request-annotations">
        <div>
          <%= form.label :category %>
          <%= form.select :category_id, category_select_options(selected: pull_request.category_id)  %>
        </div>
        <div>
          <%= form.label :test_priority, "Test Priority" %>
          <%= form.select :test_priority, options_for_select(PullRequest.test_priorities.keys, pull_request.test_priority) %>
        </div>
    </div>
        <div class="pull-request-notes">
          <%= form.markdown_field :notes %>
        </div>
        <div class="pull-request-editor">
          <%= link_to "Cancel", pull_request, class: "button" %>
          <%= form.submit %>
        </div>
    </div>
  </div>
<% end %>

app/views/pull_requests/_pull_request.html.erb
<div class="pull-request-box">
  <div class="pull-request-info">
    <%= link_to "#{pull_request.repository}\##{pull_request.number}", pull_request.url %>

    <div><%= pull_request.title %></div>
    <div class="pull-request-time"><%= pull_request.merged_at&.strftime("%Y-%m-%d %H:%M") %></div>
  </div>
  <div class="pull-request-annotations">
    <div>
      Category: <strong><%= pull_request.category.name %></strong>
    </div>
    <div>
      Test Priority:  <%= pull_request.test_priority.humanize %>
    </div>
  </div>
  <div class="pull-request-notes"><%= pull_request.notes %></div>
  <%= link_to "Edit this pull request", edit_pull_request_path(pull_request) %>
</div>

app/views/pull_requests/edit.html.erb
<%= turbo_frame_tag @pull_request do %>
  <%= render "form", pull_request: @pull_request %>
<% end %>

app/views/pull_requests/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bitcoin Core 27.0 Release Candidate Test Guide</h1>
<h3>PR Notes</h3>

<%= form_with class: "sort-selectors-form", url: sorted_pull_requests_path(),
              method: :post,
              data: {
                "turbo-frame": "pull-requests-index",
                "controller": "submit-on-change",
                "action": "change->submit-on-change#change",
                "submit-on-change-target": "form"
              } do |form| %>
  <div>
    <%= form.label :sort, "Sort by" %>
    <%= form.select :sort, pull_request_sort_select_options(selected: @sort) %>
  </div>
  <div>
    <%= form.label :sort, "Direction" %>
    <%= form.select :order,
                    options_for_select([["Ascending", "asc"],
                                        ["Descending", "desc"],
                                        ], @order) %>
  </div>

  <% if false %>
  <div>
    <%= form.label :category_filters, "Categories" %>
    <%= form.select :category_filters,
                    options_from_collection_for_select(Category.all, :id, :pretty_name),
                    {multiple: true},
                    { 'multiselect-select-all': "true"} %>
  </div>
  <% end %>
<% end %>

<%= turbo_frame_tag "pull-requests-index", class:"pull-requests-index" do %>
  <% @pull_requests.each do |pull_request| %>
    <%= turbo_frame_tag pull_request, src: pull_request_path(pull_request),
                        loading: :lazy, refresh: "morph",
                        class: "pull-request-container" do %>
      <div class="pull-request-box">
        <div class="pull-request-info">
        </div>
        <div class="pull-request-annotations">
        </div>
        <div class="pull-request-notes">
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/pull_requests/new.html.erb
<h1>New pull request</h1>

<%= render "form", pull_request: @pull_request %>

<br>

<div>
  <%= link_to "Back to pull requests", pull_requests_path %>
</div>

app/views/pull_requests/show.html.erb
<p style="color: green"><%= notice %></p>

<%= turbo_frame_tag @pull_request do %>
  <%= render @pull_request %>
<% end %>

<div>
  <%= link_to "Edit this pull request", edit_pull_request_path(@pull_request) %> |
  <%= link_to "Back to pull requests", pull_requests_path %>

  <%= button_to "Destroy this pull request", @pull_request, method: :delete %>
</div>